version: '3.6'
services:
  graph-snapper:
    command: /bin/sh -c "export GIT_COMMIT=$$(git rev-parse HEAD)"
    build:
      context: ..
      dockerfile: build/Dockerfile
      args:
        CONFIG_FILE: "compose/graph-snapper-conf_compose.json"
        GIT_COMMIT: $GIT_COMMIT
    depends_on:
      - nosql
    ports:
      - "70:8080"
  nosql:
    ulimits:
      nofile: 90000
    image: "aerospike:5.0.0.4"
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    volumes:
      - ./aerospike.conf:/etc/aerospike/aerospike.conf
configs:
  aerospike:
    file: ./aerospile.conf