basePath: /api/v1
definitions:
  credentials.GrafanaDbUser:
    properties:
      apikey:
        type: string
      description:
        type: string
      key:
        type: string
    type: object
  credentials.StoredUsers:
    properties:
      grafanaUsers:
        items:
          $ref: '#/definitions/credentials.GrafanaDbUser'
        type: array
    type: object
  health.Ping:
    properties:
      response:
        example: hello
        type: string
    type: object
  view.AccountViewV1:
    properties:
      Alias:
        description: Optional arg. Won't be returned if missing.
        type: string
      Email:
        type: string
    type: object
  view.CredentialsView1:
    properties:
      GrafanaUsers:
        additionalProperties:
          $ref: '#/definitions/view.GrafanaUser'
        type: object
    type: object
  view.GrafanaUser:
    properties:
      Description:
        type: string
    type: object
  view.MetadataView1:
    properties:
      CreateTimeUTC:
        type: string
      LastUpdate:
        type: string
      PrimaryKey:
        type: string
      version:
        type: string
    type: object
  view.RecordViewV1:
    properties:
      Account:
        $ref: '#/definitions/view.AccountViewV1'
        type: object
      Credentials:
        $ref: '#/definitions/view.CredentialsView1'
        type: object
      Metadata:
        $ref: '#/definitions/view.MetadataView1'
        type: object
    type: object
info:
  contact: {}
  description: Takes and updates snapshots from a graph service to a document store
  license:
    name: MIT License
  title: Graph Snapper API
  version: "1.0"
paths:
  /account/:id:
    put:
      description: Non-authenticated endpoint creates an empty record at the specified key. Overwrites any record that already exists
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: Create account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/view.AccountViewV1'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Create account record
      tags:
      - account
  /account/{id}:
    get:
      description: Non-authenticated endpoint fetches account at specified key
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/view.RecordViewV1'
      summary: Get account record
      tags:
      - account
  /credentials/:accountId/batch:
    post:
      description: Non-authenticated endpoint which stores the provided credentials credentials owned by a specified account. Verifies connectivity before storing in Aerospike
      parameters:
      - description: Account ID
        in: path
        name: accountId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/credentials.StoredUsers'
      summary: Create users endpoint
      tags:
      - credentials
  /health/hello:
    get:
      description: Non-authenticated endpoint that returns 200 with hello message. Used to validate that the service is responsive.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/health.Ping'
      summary: Hello sanity endpoint
      tags:
      - health
swagger: "2.0"
