basePath: /api/view
definitions:
  credentials.GrafanaDbUser:
    properties:
      apikey:
        type: string
      description:
        type: string
      key:
        type: string
    type: object
  credentials.StoredUsers:
    properties:
      grafanaUsers:
        items:
          $ref: '#/definitions/credentials.GrafanaDbUser'
        type: array
    type: object
  health.Ping:
    properties:
      response:
        example: hello
        type: string
    type: object
  v1.Account:
    properties:
      alias:
        type: string
      email:
        type: string
    type: object
info:
  contact: {}
  description: Takes and updates snapshots from a graph service to a document store
  license:
    name: MIT License
  title: Graph Snapper API
  version: "1.0"
paths:
  /account/{id}:
    put:
      description: Non-authenticated endpoint creates an empty record at the specified key. Overwrites any record that already exists
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: Create account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/view.Account'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Create account record
      tags:
      - account
  /credentials/{accountId}/batch:
    post:
      description: Non-authenticated endpoint which stores the provided credentials credentials owned by a specified account. Verifies connectivity before storing in Aerospike
      parameters:
      - description: Account ID
        in: path
        name: accountId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/credentials.StoredUsers'
      summary: Create users endpoint
      tags:
      - credentials
  /health/hello:
    get:
      description: Non-authenticated endpoint that returns 200 with hello message. Used to validate that the service is responsive.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/health.Ping'
      summary: Hello sanity endpoint
      tags:
      - health
swagger: "2.0"
